# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /flights:
    get:
      operationId: "flights.read_all"
      tags:
        - "Flights"
      summary: "Read the list of flights"
      responses:
        "200":
          description: "Successfully read flight list"